backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleemfd/localGatsbyCMS
media_folder: static/assets
public_folder: /assets

collections:
  - name: slider
    label: Slider
    label_singular: Slider Image
    folder: src/pages/posts/slider/
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }

