backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleemfd/localGatsbyCMS
media_folder: static/assets
public_folder: /assets

collections:
  - name: slider
    label: Slider
    label_singular: Slider Image
    folder: src/pages/posts/slider/
    summary: '{{title}}'
    create: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Slider Image'
        name: 'image'
        widget: 'image'
        required: true
        tagname: ''
      - {
          label: 'Tags',
          name: 'tag',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

